spring.application.name=agendamento

# Configuração do Servidor
server.port=9090

# Configuração do Banco de Dados H2 (em memória)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.datasource.url=jdbc:h2:mem:agendamentodb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Configuração do GraphQL
spring.graphql.graphiql.enabled=true
spring.graphql.schema.locations=classpath:graphql/

# Configuração do RabbitMQ
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=user
spring.rabbitmq.password=123456

# Nome da fila para notificações
rabbitmq.queue.name=notificacoes.queue