# Perfil Docker

# Configuracao do Banco de Dados PostgreSQL
spring.datasource.url=jdbc:postgresql://historico-db:5432/historico
spring.datasource.driverClassName=org.postgresql.Driver
spring.datasource.username=historico
spring.datasource.password=historico123
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Configuracao do RabbitMQ
spring.rabbitmq.host=${RABBITMQ_HOST:rabbitmq}
spring.rabbitmq.port=${RABBITMQ_PORT:5672}
spring.rabbitmq.username=${RABBITMQ_USERNAME:admin}
spring.rabbitmq.password=${RABBITMQ_PASSWORD:admin123}

# Configuracao do GraphQL
spring.graphql.graphiql.enabled=false
spring.graphql.schema.locations=classpath:/