spring.application.name=historico-service
server.port=9092


# Configuracao do RabbitMQ (desabilitado temporariamente para desenvolvimento local)
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=admin
spring.rabbitmq.password=admin123

# Habilita o GraphiQL para testes locais
spring.graphql.graphiql.enabled=true
spring.graphql.schema.locations=classpath:graphql/

# Configuracao da fila do RabbitMQ
rabbitmq.queue.name=historico.queue
rabbitmq.exchange.name=historico.exchange
rabbitmq.routing.key=historico.consulta