# Configuracao Local (padrao)
spring.application.name=agendamento

# Configuracao do Servidor
server.port=9090

# Configuracao do GraphQL
spring.graphql.graphiql.enabled=true
spring.graphql.schema.locations=classpath:graphql/

# Configuracao do RabbitMQ (desabilitado temporariamente)
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=admin
spring.rabbitmq.password=admin123


# Configuracao RabbitMQ para notificacoes
rabbitmq.queue.name=notificacoes.queue
rabbitmq.exchange.name=notificacoes.exchange
rabbitmq.routing.key=notificacao.consulta

# Filas RabbitMQ
rabbitmq.queue.notificacoes.name=notificacoes.queue
rabbitmq.queue.historico.name=historico.queue


# Logging
logging.level.com.challenge.agendamento=DEBUG
logging.level.org.springframework.amqp=DEBUG