# Configuracao Docker
spring.application.name=agendamento
spring.profiles.active=docker

# Configuracao do Servidor
server.port=9090
# Configuracao do Banco de Dados PostgreSQL

spring.datasource.url=${DATABASE_URL:jdbc:postgresql://agendamento-db:5432/agendamento}
spring.datasource.username=agendamento
spring.datasource.password=agendamento123
spring.datasource.driverClassName=org.postgresql.Driver

# JPA Configuration
spring.jpa.hibernate.ddl-auto=create-drop

# Executar data.sql APÓS o Hibernate criar o schema
spring.jpa.defer-datasource-initialization=true

# Modo de inicialização SQL
spring.sql.init.mode=always

# Mostrar SQLs para debug
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Configuracao do GraphQL
spring.graphql.graphiql.enabled=false
spring.graphql.schema.locations=classpath:graphql/

# Configuracao do RabbitMQ
spring.rabbitmq.host=rabbitmq
spring.rabbitmq.port=5672
spring.rabbitmq.username=admin
spring.rabbitmq.password=admin123

# Configuracao RabbitMQ para notificacoes
rabbitmq.queue.name=notificacoes.queue
rabbitmq.exchange.name=notificacoes.exchange
rabbitmq.routing.key=notificacao.consulta
# Nomes das filas
rabbitmq.queue.notificacoes.name=notificacoes.queue
rabbitmq.queue.historico.name=historico.queue

# Actuator
management.endpoints.web.exposure.include=health,info,metrics
management.endpoint.health.show-details=always

# Logging
logging.level.com.challenge.agendamento=INFO
logging.level.org.springframework.amqp=INFO